const mongoose = require("mongoose");
module.exports = new mongoose.Schema({
  daycareName: { type: String, trim: true, maxlength: 120 },
  logo: { type: String, trim: true },
  email: { type: String, trim: true, lowercase: true },
  phone: { type: String, trim: true },
  alternatePhone: { type: String, trim: true },
  address: { type: String, trim: true },
  city: { type: String, trim: true },
  province: { type: String, trim: true },
  country: { type: String, trim: true },
  postalCode: { type: String, trim: true },
  website: { type: String, trim: true },
  description: { type: String, trim: true },
  openingTime: { type: String, trim: true },
  closingTime: { type: String, trim: true },
  workingDays: [{ type: String, enum: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] }],
  emergencyContact: { type: String, trim: true },
  licenseNumber: { type: String, trim: true },
  defaultMonthlyFee: { type: Number, min: 0, default: 0 },
  registrationFee: { type: Number, min: 0, default: 0 },
  lateFee: { type: Number, min: 0, default: 0 },
  attendanceGraceMinutes: { type: Number, min: 0, default: 0 },
  notifyParentsOnAttendance: { type: Boolean, default: true },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
}, { timestamps: true });
