const express = require("express");
const controller = require("../controllers/daycareManagementController");
const requireManagementPermission = require("../middleware/requireManagementPermission");
const requireRole = require("../middleware/requireRole");

const router = express.Router();
router.get("/overview", requireManagementPermission("read"), controller.getOverview);
router.get("/settings", requireManagementPermission("read"), controller.getSettings);
router.put("/settings", requireManagementPermission("update"), controller.saveSettings);
router.put("/security/password", controller.changePassword);
router.get("/account", controller.getAccountProfile);
router.put("/account", controller.updateAccountProfile);
router.post("/account/photo", express.raw({ type: ["image/jpeg", "image/png", "image/webp"], limit: "3mb" }), controller.uploadAccountPhoto);
router.get("/account/photo", controller.getAccountPhoto);
router.delete("/account/photo", controller.deleteAccountPhoto);
router.get("/users", requireRole("daycare"), controller.listUsers);
router.post("/users", requireRole("daycare"), controller.createUser);
router.put("/users/:userId", requireRole("daycare"), controller.updateUser);
router.delete("/users/:userId", requireRole("daycare"), controller.deleteUser);
router.post("/parents/:parentId/reset-password", requireRole("daycare"), controller.resetParentPassword);
router.post("/logout", requireManagementPermission("read"), controller.logLogout);
router.post("/documents/files", requireManagementPermission("create"), express.raw({ type: ["application/pdf", "image/jpeg", "image/png", "image/webp"], limit: "10mb" }), controller.uploadDocument);
router.get("/documents/:recordId/file", requireManagementPermission("read"), controller.downloadDocument);
router.get("/:module/:recordId/photo", requireManagementPermission("read"), controller.getProfilePhoto);
router.post("/:module/:recordId/photo", requireManagementPermission("update"), express.raw({ type: ["image/jpeg", "image/png", "image/webp"], limit: "3mb" }), controller.uploadProfilePhoto);
router.post("/fees/:recordId/payments", requireManagementPermission("update"), controller.recordFeePayment);
router.patch("/bookings/:recordId/status", requireManagementPermission("update"), controller.updateBookingStatus);
router.get("/:module", requireManagementPermission("read"), controller.listRecords);
router.post("/:module", requireManagementPermission("create"), controller.createRecord);
router.put("/:module/:recordId", requireManagementPermission("update"), controller.updateRecord);
router.delete("/:module/:recordId", requireManagementPermission("delete"), controller.deleteRecord);

module.exports = router;
